// Package timetable turns the per-Zenturie iCalendar exports (generated by
// sked.de, linked from /studium/bachelor/stundenplaene) into queryable events.
package timetable

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/Raindancer118/nak-api/internal/client"
	"github.com/Raindancer118/nak-api/internal/stundenplan"
)

var Berlin = func() *time.Location {
	l, err := time.LoadLocation("Europe/Berlin")
	if err != nil {
		return time.FixedZone("CET", 3600)
	}
	return l
}()

type Event struct {
	UID      string    `json:"uid"`
	Start    time.Time `json:"start"`
	End      time.Time `json:"end"`
	Kind     string    `json:"kind"` // V, WP, Z, … (first token of "Veranstaltung")
	KindName string    `json:"kind_name,omitempty"`
	ModuleNr string    `json:"module_nr,omitempty"`
	Title    string    `json:"title"`
	Lecturer string    `json:"lecturer,omitempty"`
	Room     string    `json:"room,omitempty"`
	Pause    string    `json:"pause,omitempty"`
	Note     string    `json:"note,omitempty"`
	Status   string    `json:"status,omitempty"`
	Source   string    `json:"source,omitempty"` // ics file name
}

var kindNames = map[string]string{
	"V": "Vorlesung", "Ü": "Übung", "WP": "Wahlpflichtmodul", "Z": "Zenturienbetreuung",
	"K": "Klausur", "P": "Prüfung", "S": "Seminar", "T": "Tutorium",
}

var moduleRe = regexp.MustCompile(`^[A-Z]{1,3}\d{2,4}[a-z]?$`)

// ParseICS parses VEVENTs. Only the properties sked.de emits are interpreted.
func ParseICS(data string) ([]Event, error) {
	lines := unfold(data)
	var out []Event
	var cur map[string]string
	var curParams map[string]string
	for _, l := range lines {
		switch l {
		case "BEGIN:VEVENT":
			cur, curParams = map[string]string{}, map[string]string{}
			continue
		case "END:VEVENT":
			if cur != nil {
				e, err := toEvent(cur, curParams)
				if err != nil {
					return nil, err
				}
				out = append(out, e)
			}
			cur = nil
			continue
		}
		if cur == nil {
			continue
		}
		i := strings.IndexByte(l, ':')
		if i < 0 {
			continue
		}
		name, params := l[:i], ""
		if j := strings.IndexByte(name, ';'); j >= 0 {
			name, params = name[:j], name[j+1:]
		}
		cur[name] = l[i+1:]
		curParams[name] = params
	}
	return out, nil
}

func unfold(data string) []string {
	data = strings.ReplaceAll(data, "\r\n", "\n")
	raw := strings.Split(data, "\n")
	var out []string
	for _, l := range raw {
		if (strings.HasPrefix(l, " ") || strings.HasPrefix(l, "\t")) && len(out) > 0 {
			out[len(out)-1] += l[1:]
			continue
		}
		out = append(out, l)
	}
	return out
}

func unescape(s string) string {
	return strings.NewReplacer(`\n`, "\n", `\N`, "\n", `\,`, ",", `\;`, ";", `\\`, `\`).Replace(s)
}

func toEvent(p, params map[string]string) (Event, error) {
	e := Event{UID: p["UID"], Room: unescape(p["LOCATION"])}
	var err error
	if e.Start, err = parseTime(p["DTSTART"], params["DTSTART"]); err != nil {
		return e, fmt.Errorf("event %s: DTSTART: %w", e.UID, err)
	}
	if e.End, err = parseTime(p["DTEND"], params["DTEND"]); err != nil {
		return e, fmt.Errorf("event %s: DTEND: %w", e.UID, err)
	}
	desc := map[string]string{}
	for _, l := range strings.Split(unescape(p["DESCRIPTION"]), "\n") {
		if k, v, ok := strings.Cut(l, ":"); ok {
			v = strings.TrimSpace(v)
			if v == "-" {
				v = ""
			}
			desc[strings.TrimSpace(k)] = v
		}
	}
	course := desc["Veranstaltung"]
	if course == "" {
		course, _, _ = strings.Cut(unescape(p["SUMMARY"]), ",")
	}
	fields := strings.Fields(course)
	if len(fields) > 1 {
		e.Kind, fields = fields[0], fields[1:]
		if len(fields) > 1 && fields[0] == e.Kind { // "WP WP Digital Commerce"
			fields = fields[1:]
		}
		if len(fields) > 1 && moduleRe.MatchString(fields[0]) {
			e.ModuleNr, fields = fields[0], fields[1:]
		}
	}
	e.Title = strings.Join(fields, " ")
	e.KindName = kindNames[e.Kind]
	e.Lecturer = desc["Dozent"]
	e.Pause = desc["Pause"]
	e.Note = desc["Anmerkung"]
	e.Status = desc["Status"]
	if r := desc["Raum"]; r != "" {
		e.Room = r
	}
	return e, nil
}

func parseTime(v, params string) (time.Time, error) {
	if strings.HasSuffix(v, "Z") {
		return time.Parse("20060102T150405Z", v)
	}
	loc := Berlin
	for _, p := range strings.Split(params, ";") {
		if tz, ok := strings.CutPrefix(p, "TZID="); ok {
			if l, err := time.LoadLocation(tz); err == nil {
				loc = l
			}
		}
	}
	if len(v) == 8 {
		return time.ParseInLocation("20060102", v, loc)
	}
	return time.ParseInLocation("20060102T150405", v, loc)
}

type Query struct {
	From, To time.Time // zero = unbounded; To is exclusive
	Kind     string
	ModuleNr string
	Text     string // case-insensitive match on title, lecturer, room
	// ExcludeWPExcept drops WP events whose title matches none of these names
	// (the Zenturie plan lists every elective, not only the chosen ones).
	ExcludeWPExcept []string
}

func Filter(evs []Event, q Query) []Event {
	var out []Event
	text := strings.ToLower(q.Text)
	for _, e := range evs {
		if !q.From.IsZero() && e.End.Before(q.From) {
			continue
		}
		if !q.To.IsZero() && !e.Start.Before(q.To) {
			continue
		}
		if q.Kind != "" && !strings.EqualFold(e.Kind, q.Kind) {
			continue
		}
		if q.ModuleNr != "" && !strings.EqualFold(e.ModuleNr, q.ModuleNr) {
			continue
		}
		if text != "" && !strings.Contains(strings.ToLower(e.Title+" "+e.Lecturer+" "+e.Room+" "+e.ModuleNr), text) {
			continue
		}
		if q.ExcludeWPExcept != nil && e.Kind == "WP" && !matchesAny(e.Title, q.ExcludeWPExcept) {
			continue
		}
		out = append(out, e)
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Start.Before(out[j].Start) })
	return out
}

func matchesAny(title string, names []string) bool {
	t := normalize(title)
	for _, n := range names {
		if n = normalize(n); n != "" && (strings.Contains(t, n) || strings.Contains(n, t)) {
			return true
		}
	}
	return false
}

func normalize(s string) string {
	s = strings.ToLower(s)
	s = strings.TrimPrefix(s, "wp ")
	return strings.Join(strings.Fields(s), " ")
}

// Fetch downloads and merges every .ics of the Zenturie (e.g. "I23a" matches
// "I23a_6.ics" and "I23a_7.ics"); events are deduplicated by UID.
func Fetch(c *client.Client, zenturie string) ([]Event, []string, error) {
	plans, err := stundenplan.FetchList(c)
	if err != nil {
		return nil, nil, err
	}
	var files []string
	seen := map[string]bool{}
	var all []Event
	for _, p := range plans {
		if p.Format != "ics" || !(strings.EqualFold(p.Zenturie, zenturie) || strings.HasPrefix(strings.ToLower(p.Zenturie), strings.ToLower(zenturie)+"_")) {
			continue
		}
		data, _, _, err := c.Download(p.URL)
		if err != nil {
			return nil, nil, fmt.Errorf("download %s: %w", p.Filename, err)
		}
		evs, err := ParseICS(string(data))
		if err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", p.Filename, err)
		}
		files = append(files, p.Filename)
		for _, e := range evs {
			if seen[e.UID] {
				continue
			}
			seen[e.UID] = true
			e.Source = p.Filename
			all = append(all, e)
		}
	}
	if len(files) == 0 {
		return nil, nil, fmt.Errorf("no .ics timetable found for Zenturie %q", zenturie)
	}
	return all, files, nil
}
